### PR TITLE
Updated mesh handling to make sharing meshes between users work

### PR DESCRIPTION
**Pull request by bbbales2**
I made these two changes:

1 . Each mesh in a users library has a 'ghost' property. 'ghost'" meshes move around the system but are not shown in the GUI. When meshes are deleted from the system, the references are simply labeled as ghosts, so the user doesn't see them, but none of the models lose their reference to the actual meshes.

Meshes imported from files are by default ghosted (so are the example models). I could change that behavior if it is desirable.

2 . Whenever a model is updated in the handler on the server, the server makes sure that the user has a reference to the mesh. This gets triggered when a user tells the GUI to copy a model from the public library. On saving that model, the server realizes that the user doesn't have access to the mesh and builds the necessary reference.

If a model's mesh is ghosted when it is copied to the public library, copies of that mesh that make it elsewhere are also ghosted. If it isn't ghosted, then it won't be when copies are made.

I hope my appropriation of the word ghost here is nice and confusing.

### CODE REVIEW

**Comment by bbbales2** [comment]
This fixes https://github.com/StochSS/stochss/issues/311

**Comment by briandrawert** [comment]
This pull fixes the original bug, but creates a new confusing behavior.  It is now possible to delete the currently selected mesh that a model is using, and the model will still display, run, and visualize properly.  However, when you look at the model in the model editor page, it looks like no mesh has been selected (under "select a mesh").  The mesh preview, still shows the correct (deleted) mesh (see screen shot below).  The simplest fix would be to prevent the user from deleting the currently selected mesh.
ss

**Comment by bbbales2** [comment]
The issue here is that models are allowed to have meshes that are visibly part of their mesh library now.

For instance, on model import from file, the mesh remains hidden (I did this to avoid getting tons of copies of the same mesh, because importing from file deep copies). Also, if the mesh was hidden when it was exported to public library, whoever imports it won't get a visible copy of the mesh in their public library.

I can disable the delete button, but this issue comes up elsewhere.

There are two options I see (on top of disabling the delete button):

1. All meshes are always visible
2. There used to be a third collapseable with 'select a mesh' and 'upload a mesh' that was simply the mesh name and description. So this state is reachable, but it's a little less confusing. I could switch to that.

**Comment by bbbales2** [comment]
Deletes disabled!

Also by default a little "Current Mesh" box is shown that shows the chosen mesh and its description.

I did not make the name and description editable.

**Comment by briandrawert** [comment]
I think this is a significant improvement, but I found 2 problems. 
1) After I delete a mesh, I re-import the model from the public library (only way to get the mesh back) but the mesh doesn't appear in the select mesh list.
2) In the select mesh tab, it never collapses to the current mesh tab (indicator of completed action). Can we have a "OK/Cancel" button or similar that collapses the tab?

**Comment by bbbales2** [comment]
Re 1), this is expected.

Once a mesh is deleted from the library, all the other models that use it still keep a reference to to the mesh (including public models).

Import from public library respects the delete-status of the meshes referenced by the models.

With that said, I could make import from public library make the imported mesh visible.

This still doesn't prevent a user from arriving at a state where the model is defined and works but the mesh is not in the selection list.

Another question is should models imported from .zip also expose their meshes by default?

Whatcha think? I'm good with just making import from public library meshes visible and stopping there. Making import from .zip meshes visible can get messy, but I can also see where it's a desired thing.

The counter point is, if the mesh is vulnerable to being deleted, it came from outside StochSS. So if it's needed in StochSS again it can always be imported. Or something close to that.

Re 2), yeah I don't mind adding an Okay button. I don't want to autoclose it on select, but an Okay button seems innocuous enough.

**Comment by briandrawert** [comment]
On Mar 23, 2015, at 3:00 PM, bbbales2 <notifications@github.com> wrote:

> Re 1),  I'm good with just making import from public library meshes visible and stopping there. Making import from .zip meshes visible can get messy, but I can also see where it's a desired thing
> 
I think making them visible both on import from public library or zip is the right way to go.  We need a way to 'undo' the delete, and importing from zip is one of the easiest way to move a mesh from one installation to another.

**Comment by bbbales2** [comment]
Sure, this seems fine.

**Comment by bbbales2** [comment]
Yo Brian, if you get a chance, check this out.

**Comment by briandrawert** [comment]
When I try to copy the 'cylinder demo' model from the public library I get the following stack trace:
ERROR    2015-03-28 18:09:26,752 wsgi.py:278]
Traceback (most recent call last):
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/google/appengine/runtime/wsgi.py", line 266, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1519, in __call__
    response = self._internal_error(e)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/Users/brian/Desktop/research/stochss.develop/app/stochssapp.py", line 175, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Users/brian/Desktop/research/stochss.develop/sdk/python/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/Users/brian/Desktop/research/stochss.develop/app/handlers/modeleditor.py", line 439, in post
    modelId = ModelManager.updateModel(self, jsonModel)
  File "/Users/brian/Desktop/research/stochss.develop/app/handlers/modeleditor.py", line 364, in updateModel
    if meshDbCurrent.userId != userID:

**Comment by bbbales2** [comment]
I tested this on my copy of StochSS with two accounts, and then on a clean
install as well, and I did not get this error.

What I suspect is happening is somehow your cylinder_demo mesh was deleted
from your datastore before we added the mechanisms to prevent model
deletion, and now 'meshDbCurrent' doesn't exist in the db so
meshDbCurrent.userId is a bad reference for you.

I think this will go away if you clear your datastore. Since there's no way
to really delete meshes anymore, I don't think there's any reason to add
any more fail safes server side.

**Comment by briandrawert** [comment]
Yup, I deleted my datastore and I could not replicate the problem.

**Pull request merged**
