### PR TITLE
Scripts to run StochSS from within the OSX package with embeded python

### PR DESCRIPTION
**Pull request by briandrawert**

### CODE REVIEW

**Comment by briandrawert** [comment]
This can be tested with the package: http://hydra.cs.ucsb.edu/stochss/StochSS-1.5-embeded-python-rc7.zip

**Comment by bbbales2** [comment]
I tested all jobs local and in the cloud and things seemed to work.

But, I kept getting tons of those "Do you want to allow 'python' to accept incoming web request?" message boxes.

Every time I'd load the output of a 3D job I'd get them. I think they corresponded to whenever the javascript made a request back to the server.

Did you get those too?

**Comment by briandrawert** [comment]
I've never gotten them on my computer, but I sometimes get them on other computers.  I will look into it and see what I can learn.

**Comment by briandrawert** [comment]
I am able to replicate this behavior.  The answer is interesting and problematic.  When the OSX firewall is on, any new incoming connection must be authorized by the user.  Hence the "Do you want to allow 'python' to accept incoming web request?" messages.  On those dialogs, when you click 'allow', that apparently gives permission for that version of the .app folder to make connections.  When any files change inside the .app folder (say "mydatastore", or the output directory), that permission is no longer valid and the firewall will ask permission again.  This means we need to re-think how we organize the app on OSX.

Ref: http://superuser.com/questions/100013/why-does-the-mac-os-x-firewall-dialog-recurringly-pop-up-and-disappear-by-itself

**Comment by ahellander** [comment]
Can't we just change it so that the location of the datastore file and the output is configurable and sits outside the app bundle? I think at least moving output outside of it makes a lot of sense for other reasons as well.

**Pull request merged**
