### PR TITLE
Model editor2

### PR DESCRIPTION
**Pull request by bbbales2**
Let the model editor review begin!

~~I still haven't implemented the reaction editor changes that we discussed.~~ Fixed https://github.com/StochSS/stochss/commit/28caed469a7eacb35472c647e2651226bae9b01d

~~Also the mesh editor is missing Debjani's controls.~~ Fixed https://github.com/StochSS/stochss/commit/f97bdce3436f455ec8adf5251ab49e146defe9b3 ... https://github.com/StochSS/stochss/commit/00d53d7b4f142e7a75c0a4dd3cc17966d0924753

~~Also the styling and instructions for convertToPopulation are very vague. Basically, click the link *once* and you'll see the proposed model changes. Click it *twice* and the convert will happen.~~ Fixed https://github.com/StochSS/stochss/commit/9599a9609927fa7141714d0120535c01014c8e80

Any comments accepted!

### CODE REVIEW

**Comment by bbbales2** [comment]
Oh also the import/export won't work yet.

**Comment by bbbales2** [comment]
Also missing:

* Model renaming
* When species/parameters are renamed, all appropriate select menus do not update yet

**Comment by bbbales2** [comment]
* Put message on screen telling the user when the model is saving

**Comment by bbbales2** [comment]
* Need to get example modes in
* https://github.com/StochSS/stochss/issues/273

**Comment by bbbales2** [comment]
* I think there is some sort of WebGL memory leak happening. Getting error: "WARNING: Too many active WebGL contexts. Oldest context will be lost." after too many model switches

**Comment by bbbales2** [comment]
* If a mesh is deleted while still in use by a model, there is an error

**Comment by bbbales2** [comment]
* After selecting new mesh mesh preview freezes

**Comment by bbbales2** [comment]
* The heat shock model is absurdly slow in the new editor. Gotta figure this out...

**Comment by briandrawert** [comment]
The "radio button" to edit models should be a "blue" button that says "edit".

Also, when I create a new model, I should be to editing that model automatically.

**Comment by bbbales2** [comment]
* Can delete example models from public library

**Comment by briandrawert** [comment]
When editing species/parameters/reactions, the "Previous 10" [0 / 9] "Next 10" buttons should only be shown if there are more than 10 items.

Also, when you add a new item in the box "[ 0 / X]" , the value of X does not change until "Previous" or "Next" are pressed.

**Comment by briandrawert** [comment]
Can't add custom propensities, "add" button is disabled.

**Comment by briandrawert** [comment]
In the reaction, it is not obvious that the "edit" button on the right shows and hides the area to edit the "Reactants" and "Products".

I would remove the column name "Latex", that is confusing and probably unnecessary.

It would be helpful to make it so that you can only edit one reaction at a time, so that "edit" on a different reaction would collapse the edit box on all other reactions.

It might be more straightforward to have the edit box contain all the information: name, mass-action/custom, parameter/custom propensity, reactants, products.  When a reaction is not currently being edited, then it shows a non-editable summary including what is currently the "Latex" display (which could be hidden when in edit mode).

Also, it would be helpful to add a dialog confirm "Are you sure you want to delete the reaction 'r1'", when you click the delete button.  Same for Species and Parameters.

**Comment by briandrawert** [comment]
Species editor, spatial models: 
- "Diffusion" column name should be "Diffusion Coefficient"
- "Subdomains" is too short to know what it refers to.
- Mesh visualization is not working.  When I check/uncheck the checkboxes under "Display Subdomains" then I get the javascript error:
"app.bundle.js:1283 Uncaught TypeError: Cannot read property 'geometry' of undefined"
- Under "Initial Conditions Editor": 
  =>  it says "Add Reaction", should be "initial condition"
  => it is confusing to have the add initial condition just add a "type", we should have both species and type for the add.

**Comment by bbbales2** [comment]
* Convert to population isn't very pretty
* Uploading custom meshes not working

**Comment by bbbales2** [comment]
* Select a model, duplicate it, convert the duplicate to population, delete the population model, select the original, and duplicate it. This creates 2 duplicates instead of one
* When changing species stoichiometries the model isn't saving

**Comment by bbbales2** [comment]
* Changing models causes inconsistent behaviour from the left/right buttons

**Comment by bbbales2** [comment]
* Paginate initial conditions

**Comment by briandrawert** [comment]
When adding a spatial model, the mesh editor tab should open after 'add' is clicked, not the species editor

**Comment by briandrawert** [comment]
when I import a 'zip' model, I got red box with "Server error importing file"
```
ERROR    2015-02-09 20:39:00,493 wsgi.py:278]
Traceback (most recent call last):
  File "/Users/brian/Desktop/research/stochss-modeleditor2/stochss/sdk/python/google/appengine/runtime/wsgi.py", line 266, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/Users/brian/Desktop/research/stochss-modeleditor2/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 1519, in __call__
    response = self._internal_error(e)
  File "/Users/brian/Desktop/research/stochss-modeleditor2/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/brian/Desktop/research/stochss-modeleditor2/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/brian/Desktop/research/stochss-modeleditor2/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Users/brian/Desktop/research/stochss-modeleditor2/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/Users/brian/Desktop/research/stochss-modeleditor2/stochss/app/stochssapp.py", line 175, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/Users/brian/Desktop/research/stochss-modeleditor2/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Users/brian/Desktop/research/stochss-modeleditor2/stochss/sdk/python/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/Users/brian/Desktop/research/stochss-modeleditor2/stochss/app/handlers/exportimport.py", line 1147, in post
    szip.extractStochKitModel(name, userId, self, rename = rename)
  File "/Users/brian/Desktop/research/stochss-modeleditor2/stochss/app/handlers/exportimport.py", line 404, in extractStochKitModel
    i, subdomain = line.split()
ValueError: need more than 1 value to unpack
```

**Comment by briandrawert** [comment]
Deleting a model should require a 'are you sure' dialog

**Pull request merged**
