### PR TITLE
New cost analysis

### PR DESCRIPTION
**Pull request by gmy**
New features including:
1. job reproduction
2. cost analysis
3. non-blocking mode when launching vms
4. selection of different instances type when launching vms

### CODE REVIEW

**Comment by briandrawert** [comment]
I think I found a bug.  I launched a head node and one worker node.  These booted successfully.  Next I clicked the "Launch Node" button.  This launched an "m1.micro" instance.
1.  It was confusing that is would launch that worker size.  One way to fix this would be to keep the UI on "advanced" mode once you start to launch instances using that.
2.  In the error log, I am getting a large number of "ImportError: No module named celeryconfig" errors (stack-trace omitted).  I did not get them when launching the first two nodes

**Comment by bbbales2** [comment]
I just went back to do some more testing and I'm not able to launch new nodes now!

Same credentials as I used before. The nodes just stay in a pending state. Perhaps it's one of these permissions things?

**Comment by gmy** [comment]
Yeah, it's a good idea to keep it the advanced setting mode. Previously, I thought that for the first time when the user launch a vm, it has to be at least a c3.large (head node), right? Then the worker nodes the user launch later could be some type that cost least. 

As for the "celeryconfig" errors, it comes again…!! I remember I reported it before. The error should refer to the one that in tasks.py around line 59. It cannot find the celeryconif.py. for some reason. When I modified it to be "celeryconfig.py" the error seems doesn't show up, but in master branch it should be exactly as "celeryconfig". I didn't get it in my laptop, maybe it has some cache. Brian, do you have some time tomorrow, so that we could see the error together?

**Comment by bbbales2** [comment]
Stochoptim is working on the cloud now! I think this is good to go in develop

**Comment by briandrawert** [comment]
I think this is ready to merge.

**Comment by ahellander** [comment]
Just finished testing it, looks good to me.

**Pull request merged**
