### PR TITLE
Fix for #171

### LINKED ISSUE #171: Python package dependencies
I think we should use virtualenv and pip:

http://www.jontourage.com/2011/02/09/virtualenv-pip-basics/

That way, virtualenv is the only python package that the user must have installed to use our software, and then all the python dependencies can be installed through that.

Check out the very end of that blog post where the guy talks about dependencies.txt

There are still the regular dependencies that we have to handle

Comments? Objections?

The goal is to get rid of the libraries included by source and make using obscure-but-handy python packages not a problem

### PR DESCRIPTION
**Pull request by briandrawert**
Fixes #171

### CODE REVIEW

**Comment by briandrawert** [comment]
Tested on a clean Ubuntu 12.04.5 image, the command "sudo CFLAGS="-I/usr/lib/openmpi/include/" C_INCLUDE_PATH=/usr/lib/openmpi/include  pip install h5py==2.4.0b1" fails with error "fatal error: hdf5.h: No such file or directory"

**Comment by JohnAbel** [comment]
The command shouldn't have a C_INCLUDE_PATH, try it without?

On Wed, May 20, 2015 at 1:36 PM, Brian Drawert <notifications@github.com>
wrote:

> Tested on a clean Ubuntu 12.04.5 image, the command "sudo
> CFLAGS="-I/usr/lib/openmpi/include/"
> C_INCLUDE_PATH=/usr/lib/openmpi/include pip install h5py==2.4.0b1" fails
> with error "fatal error: hdf5.h: No such file or directory"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StochSS/stochss/pull/378#issuecomment-104030296>.
>



-- 

*John H. Abel*
PhD Student, Chemical Engineering
University of California, Santa Barbara
Email: jha@engr.ucsb.edu
Tel: (401)787-4253

**Comment by JohnAbel** [comment]
should be: sudo CFLAGS="-I/usr/lib/openmpi/include/" pip install
h5py==2.4.0b1

On Wed, May 20, 2015 at 2:50 PM, John H. Abel <jha@engr.ucsb.edu> wrote:

> The command shouldn't have a C_INCLUDE_PATH, try it without?
>
> On Wed, May 20, 2015 at 1:36 PM, Brian Drawert <notifications@github.com>
> wrote:
>
>> Tested on a clean Ubuntu 12.04.5 image, the command "sudo
>> CFLAGS="-I/usr/lib/openmpi/include/"
>> C_INCLUDE_PATH=/usr/lib/openmpi/include pip install h5py==2.4.0b1" fails
>> with error "fatal error: hdf5.h: No such file or directory"
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/StochSS/stochss/pull/378#issuecomment-104030296>.
>>
>
>
>
> --
>
> *John H. Abel*
> PhD Student, Chemical Engineering
> University of California, Santa Barbara
> Email: jha@engr.ucsb.edu
> Tel: (401)787-4253
>



-- 

*John H. Abel*
PhD Student, Chemical Engineering
University of California, Santa Barbara
Email: jha@engr.ucsb.edu
Tel: (401)787-4253

**Comment by briandrawert** [comment]
I get the same result both ways.

**Comment by bbbales2** [comment]
I think the 2.4.0b1 restriction is only for Mac OS X for what it's worth.

**Comment by bbbales2** [comment]
And it looks like 2.5.0 and 2.4.0 both have binaries for Mac OS X in pypi now. Maybe it's time to upgrade those?

**Comment by briandrawert** [comment]
Sorry, but I get the same error with and without the version number.

**Pull request merged**
