### PR TITLE
Quickstart

### PR DESCRIPTION
**Pull request by BryanRumsey**
**NOT READY TO MERGE**

### CODE REVIEW

**Comment by popensesame** [comment]
Update file browser screenshot - "Options" -> "Actions"

**Comment by popensesame** [comment]
The task is to change the species mode and run a preview for each type.

**Comment by popensesame** [comment]
Maybe create the degradation model instead of use new model?

**Comment by seanebum** [comment]
Another possibility to better support a "narrative" with modifying the degradation model by an event:

We could have them initialize a second species, "protease_enzyme" with an initial value of 0.  We could also add a reaction "protein+protease_enzyme->protease_enzyme" at rate "enzymatic_degradation"=0.

The event could occur at some time such as t>15, with assignments:
protease_enzyme: 100
enzymatic_degradation=10*degradation

The narrative would be that at a certain time, a protease enzyme was added to the volume increasing the rate of degradation.

**Comment by popensesame** [comment]
Also added resource limits to jupyterhub config

**Pull request merged**
