### PR TITLE
Delete run.windows 

### PR DESCRIPTION
**Pull request by briandrawert**

### CODE REVIEW

**Comment by bbbales2** [comment]
Why rename? Can't this be deleted? Is it even accessible anymore?

**Comment by ahellander** [comment]
If we are still uploading new AMIs it should still work?

-------------------------------------------
Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Mar 2, 2016, at 12:33 AM, Ben Bales <notifications@github.com<mailto:notifications@github.com>> wrote:


Why rename? Can't this be deleted? Is it even accessible anymore?

**Comment by ahellander** [comment]
One consideration is that MOLNs is now capable of building images and deploying StochSS in AWS and OpenStack (using much similar logic to this script). Maybe it is too much to maintain both versions?  One advantage of this one is that it uses the "official" StochSS AMIs, and MOLNs instead builds new ones based on the branch of choice.

**Comment by briandrawert** [comment]
I agree, we should depreciate this, and move to the molns solution (since that is what we developers actually use).

**Pull request merged**
